import {gql} from '@apollo/client/core';

/**
 * Public Record Fragment
 */
export const PublicRecordNonFCRAReport = gql`
fragment PublicRecordNonFCRAReport on InsiderReportExp {
  PublicRecordNonFCRAReport {
    TransactionID
    Notes
InputRecord {
    FirstName
    MiddleName
    LastName
    SuffixName
    SSN
    DOB
    Address
    City
    State
    Zip
    LexID
    include_credit_report
}
BankruptcyRecords {
  BankruptcyRecord {
    bkt_case
    bkt_prcode
    bkt_fdate
    bkt_sdate
    bkt_debtor_chapter
    bkt_debtor_converted_date
    bkt_dcode
    bkt_matchcode
    bkt_fname
    bkt_mname
    bkt_lname
    bkt_suffix
    bkt_socsecnum
    bkt_address
    bkt_ccity
    bkt_sstate
    bkt_zip
    bkt_county
    bkt_dphone
    bkt_business
    bkt_business1
    bkt_business2
    bkt_business3
    bkt_law_firm
    bkt_attyname
    bkt_attyaddr
    bkt_attycity
    bkt_attystate
    bkt_attyzip
    bkt_attyphone
    bkt_attyemail
    bkt_attyfax
    bkt_trustid
    bkt_trustee
    bkt_taddr
    bkt_tcity
    bkt_tstate
    bkt_tzip
    bkt_tphone
    bkt_pet_seq
    bkt_ddismissal
    bkt_ecoa
    bkt_funds
    bkt_date341
    bkt_time341
    bkt_loc341
    bkt_bardate
    bkt_pocdate
    bkt_cfiled
    bkt_stfiled
    bkt_court
    bkt_district
    bkt_caddr1
    bkt_caddr2
    bkt_mailcity
    bkt_czip
    bkt_cphone
    bkt_reinstdate
    bkt_case_closing_date
    bkt_filingstatus
  }
}
JudgmentAndLienRecords {
  JudgmentAndLienRecord {
    jnl_filing_jurisdiction
    jnl_filing_jurisdiction_name
    jnl_orig_filing_number
    jnl_orig_filing_type
    jnl_orig_filing_date
    jnl_orig_filing_time
    jnl_case_number
    jnl_tax_code
    jnl_irs_serial_number
    jnl_release_date
    jnl_amount
    jnl_eviction
    jnl_judg_satisfied_date
    jnl_judg_vacated_date
    jnl_judge
    jnl_filing_status
    jnl_debtor_1_party_1_title
    jnl_debtor_1_party_1_fname
    jnl_debtor_1_party_1_mname
    jnl_debtor_1_party_1_lname
    jnl_debtor_1_party_1_name_suffix
    jnl_debtor_1_party_1_cname
    jnl_debtor_1_party_1_orig_name
    jnl_debtor_1_party_1_ssn
    jnl_debtor_1_party_1_tax_id
    jnl_debtor_1_party_1_address1
    jnl_debtor_1_party_1_address2
    jnl_debtor_1_party_1_p_city_name
    jnl_debtor_1_party_1_st
    jnl_debtor_1_party_1_zip
    jnl_debtor_1_party_1_zip4
    jnl_debtor_1_party_1_msa
    jnl_debtor_1_party_1_county_name
    jnl_debtor_1_party_1_phone
    jnl_debtor_1_party_2_title
    jnl_debtor_1_party_2_fname
    jnl_debtor_1_party_2_mname
    jnl_debtor_1_party_2_lname
    jnl_debtor_1_party_2_name_suffix
    jnl_debtor_1_party_2_cname
    jnl_debtor_1_party_2_ssn
    jnl_debtor_1_party_2_tax_id
    jnl_debtor_1_party_2_address1
    jnl_debtor_1_party_2_address2
    jnl_debtor_1_party_2_p_city_name
    jnl_debtor_1_party_2_st
    jnl_debtor_1_party_2_zip
    jnl_debtor_1_party_2_zip4
    jnl_debtor_1_party_2_msa
    jnl_debtor_1_party_2_county_name
    jnl_debtor_1_party_2_phone
    jnl_debtor_2_party_1_title
    jnl_debtor_2_party_1_fname
    jnl_debtor_2_party_1_mname
    jnl_debtor_2_party_1_lname
    jnl_debtor_2_party_1_name_suffix
    jnl_debtor_2_party_1_cname
    jnl_debtor_2_party_1_orig_name
    jnl_debtor_2_party_1_ssn
    jnl_debtor_2_party_1_tax_id
    jnl_debtor_2_party_1_address1
    jnl_debtor_2_party_1_address2
    jnl_debtor_2_party_1_p_city_name
    jnl_debtor_2_party_1_st
    jnl_debtor_2_party_1_zip
    jnl_debtor_2_party_1_zip4
    jnl_debtor_2_party_1_msa
    jnl_debtor_2_party_1_county_name
    jnl_debtor_2_party_1_phone
    jnl_debtor_2_party_2_title
    jnl_debtor_2_party_2_fname
    jnl_debtor_2_party_2_mname
    jnl_debtor_2_party_2_lname
    jnl_debtor_2_party_2_name_suffix
    jnl_debtor_2_party_2_cname
    jnl_debtor_2_party_2_ssn
    jnl_debtor_2_party_2_tax_id
    jnl_debtor_2_party_2_address1
    jnl_debtor_2_party_2_address2
    jnl_debtor_2_party_2_p_city_name
    jnl_debtor_2_party_2_st
    jnl_debtor_2_party_2_zip
    jnl_debtor_2_party_2_zip4
    jnl_debtor_2_party_2_msa
    jnl_debtor_2_party_2_county_name
    jnl_debtor_2_party_2_phone
    jnl_debtor_3_party_1_title
    jnl_debtor_3_party_1_fname
    jnl_debtor_3_party_1_mname
    jnl_debtor_3_party_1_lname
    jnl_debtor_3_party_1_name_suffix
    jnl_debtor_3_party_1_cname
    jnl_debtor_3_party_1_orig_name
    jnl_debtor_3_party_1_ssn
    jnl_debtor_3_party_1_tax_id
    jnl_debtor_3_party_1_address1
    jnl_debtor_3_party_1_address2
    jnl_debtor_3_party_1_p_city_name
    jnl_debtor_3_party_1_st
    jnl_debtor_3_party_1_zip
    jnl_debtor_3_party_1_zip4
    jnl_debtor_3_party_1_msa
    jnl_debtor_3_party_1_county_name
    jnl_debtor_3_party_1_phone
    jnl_debtor_3_party_2_title
    jnl_debtor_3_party_2_fname
    jnl_debtor_3_party_2_mname
    jnl_debtor_3_party_2_lname
    jnl_debtor_3_party_2_name_suffix
    jnl_debtor_3_party_2_cname
    jnl_debtor_3_party_2_ssn
    jnl_debtor_3_party_2_tax_id
    jnl_debtor_3_party_2_address1
    jnl_debtor_3_party_2_address2
    jnl_debtor_3_party_2_p_city_name
    jnl_debtor_3_party_2_st
    jnl_debtor_3_party_2_zip
    jnl_debtor_3_party_2_zip4
    jnl_debtor_3_party_2_msa
    jnl_debtor_3_party_2_county_name
    jnl_debtor_3_party_2_phone
    jnl_debtor_4_party_1_title
    jnl_debtor_4_party_1_fname
    jnl_debtor_4_party_1_mname
    jnl_debtor_4_party_1_lname
    jnl_debtor_4_party_1_name_suffix
    jnl_debtor_4_party_1_cname
    jnl_debtor_4_party_1_orig_name
    jnl_debtor_4_party_1_ssn
    jnl_debtor_4_party_1_tax_id
    jnl_debtor_4_party_1_address1
    jnl_debtor_4_party_1_address2
    jnl_debtor_4_party_1_p_city_name
    jnl_debtor_4_party_1_st
    jnl_debtor_4_party_1_zip
    jnl_debtor_4_party_1_zip4
    jnl_debtor_4_party_1_msa
    jnl_debtor_4_party_1_county_name
    jnl_debtor_4_party_1_phone
    jnl_debtor_4_party_2_title
    jnl_debtor_4_party_2_fname
    jnl_debtor_4_party_2_mname
    jnl_debtor_4_party_2_lname
    jnl_debtor_4_party_2_name_suffix
    jnl_debtor_4_party_2_cname
    jnl_debtor_4_party_2_ssn
    jnl_debtor_4_party_2_tax_id
    jnl_debtor_4_party_2_address1
    jnl_debtor_4_party_2_address2
    jnl_debtor_4_party_2_p_city_name
    jnl_debtor_4_party_2_st
    jnl_debtor_4_party_2_zip
    jnl_debtor_4_party_2_zip4
    jnl_debtor_4_party_2_msa
    jnl_debtor_4_party_2_county_name
    jnl_debtor_4_party_2_phone
    jnl_debtor_5_party_1_title
    jnl_debtor_5_party_1_fname
    jnl_debtor_5_party_1_mname
    jnl_debtor_5_party_1_lname
    jnl_debtor_5_party_1_name_suffix
    jnl_debtor_5_party_1_cname
    jnl_debtor_5_party_1_orig_name
    jnl_debtor_5_party_1_ssn
    jnl_debtor_5_party_1_tax_id
    jnl_debtor_5_party_1_address1
    jnl_debtor_5_party_1_address2
    jnl_debtor_5_party_1_p_city_name
    jnl_debtor_5_party_1_st
    jnl_debtor_5_party_1_zip
    jnl_debtor_5_party_1_zip4
    jnl_debtor_5_party_1_msa
    jnl_debtor_5_party_1_county_name
    jnl_debtor_5_party_1_phone
    jnl_debtor_5_party_2_title
    jnl_debtor_5_party_2_fname
    jnl_debtor_5_party_2_mname
    jnl_debtor_5_party_2_lname
    jnl_debtor_5_party_2_name_suffix
    jnl_debtor_5_party_2_cname
    jnl_debtor_5_party_2_ssn
    jnl_debtor_5_party_2_tax_id
    jnl_debtor_5_party_2_address1
    jnl_debtor_5_party_2_address2
    jnl_debtor_5_party_2_p_city_name
    jnl_debtor_5_party_2_st
    jnl_debtor_5_party_2_zip
    jnl_debtor_5_party_2_zip4
    jnl_debtor_5_party_2_msa
    jnl_debtor_5_party_2_county_name
    jnl_debtor_5_party_2_phone
    jnl_debtor_6_party_1_title
    jnl_debtor_6_party_1_fname
    jnl_debtor_6_party_1_mname
    jnl_debtor_6_party_1_lname
    jnl_debtor_6_party_1_name_suffix
    jnl_debtor_6_party_1_cname
    jnl_debtor_6_party_1_orig_name
    jnl_debtor_6_party_1_ssn
    jnl_debtor_6_party_1_tax_id
    jnl_debtor_6_party_1_address1
    jnl_debtor_6_party_1_address2
    jnl_debtor_6_party_1_p_city_name
    jnl_debtor_6_party_1_st
    jnl_debtor_6_party_1_zip
    jnl_debtor_6_party_1_zip4
    jnl_debtor_6_party_1_msa
    jnl_debtor_6_party_1_county_name
    jnl_debtor_6_party_1_phone
    jnl_debtor_6_party_2_title
    jnl_debtor_6_party_2_fname
    jnl_debtor_6_party_2_mname
    jnl_debtor_6_party_2_lname
    jnl_debtor_6_party_2_name_suffix
    jnl_debtor_6_party_2_cname
    jnl_debtor_6_party_2_ssn
    jnl_debtor_6_party_2_tax_id
    jnl_debtor_6_party_2_address1
    jnl_debtor_6_party_2_address2
    jnl_debtor_6_party_2_p_city_name
    jnl_debtor_6_party_2_st
    jnl_debtor_6_party_2_zip
    jnl_debtor_6_party_2_zip4
    jnl_debtor_6_party_2_msa
    jnl_debtor_6_party_2_county_name
    jnl_debtor_6_party_2_phone
    jnl_debtor_7_party_1_title
    jnl_debtor_7_party_1_fname
    jnl_debtor_7_party_1_mname
    jnl_debtor_7_party_1_lname
    jnl_debtor_7_party_1_name_suffix
    jnl_debtor_7_party_1_cname
    jnl_debtor_7_party_1_orig_name
    jnl_debtor_7_party_1_ssn
    jnl_debtor_7_party_1_tax_id
    jnl_debtor_7_party_1_address1
    jnl_debtor_7_party_1_address2
    jnl_debtor_7_party_1_p_city_name
    jnl_debtor_7_party_1_st
    jnl_debtor_7_party_1_zip
    jnl_debtor_7_party_1_zip4
    jnl_debtor_7_party_1_msa
    jnl_debtor_7_party_1_county_name
    jnl_debtor_7_party_1_phone
    jnl_debtor_7_party_2_title
    jnl_debtor_7_party_2_fname
    jnl_debtor_7_party_2_mname
    jnl_debtor_7_party_2_lname
    jnl_debtor_7_party_2_name_suffix
    jnl_debtor_7_party_2_cname
    jnl_debtor_7_party_2_ssn
    jnl_debtor_7_party_2_tax_id
    jnl_debtor_7_party_2_address1
    jnl_debtor_7_party_2_address2
    jnl_debtor_7_party_2_p_city_name
    jnl_debtor_7_party_2_st
    jnl_debtor_7_party_2_zip
    jnl_debtor_7_party_2_zip4
    jnl_debtor_7_party_2_msa
    jnl_debtor_7_party_2_county_name
    jnl_debtor_7_party_2_phone
    jnl_creditor_title
    jnl_creditor_fname
    jnl_creditor_mname
    jnl_creditor_lname
    jnl_creditor_name_suffix
    jnl_creditor_cname
    jnl_creditor_orig_name
    jnl_creditor_address1
    jnl_creditor_address2
    jnl_creditor_p_city_name
    jnl_creditor_st
    jnl_creditor_zip
    jnl_creditor_zip4
    jnl_creditor_msa
    jnl_creditor_county_name
    jnl_creditor_phone
    jnl_attorney_title
    jnl_attorney_fname
    jnl_attorney_mname
    jnl_attorney_lname
    jnl_attorney_name_suffix
    jnl_attorney_cname
    jnl_attorney_orig_name
    jnl_attorney_address1
    jnl_attorney_address2
    jnl_attorney_p_city_name
    jnl_attorney_st
    jnl_attorney_zip
    jnl_attorney_zip4
    jnl_attorney_msa
    jnl_attorney_county_name
    jnl_attorney_phone
    jnl_filing_1_filing_number
    jnl_filing_1_filing_type_desc
    jnl_filing_1_filing_date
    jnl_filing_1_filing_time
    jnl_filing_1_filing_book
    jnl_filing_1_filing_page
    jnl_filing_1_agency
    jnl_filing_1_agency_state
    jnl_filing_1_agency_city
    jnl_filing_1_agency_county
    jnl_filing_2_filing_number
    jnl_filing_2_filing_type_desc
    jnl_filing_2_filing_date
    jnl_filing_2_filing_time
    jnl_filing_2_filing_book
    jnl_filing_2_filing_page
    jnl_filing_2_agency
    jnl_filing_2_agency_state
    jnl_filing_2_agency_city
    jnl_filing_2_agency_county
    jnl_filing_3_filing_number
    jnl_filing_3_filing_type_desc
    jnl_filing_3_filing_date
    jnl_filing_3_filing_time
    jnl_filing_3_filing_book
    jnl_filing_3_filing_page
    jnl_filing_3_agency
    jnl_filing_3_agency_state
    jnl_filing_3_agency_city
    jnl_filing_3_agency_county
    jnl_filing_4_filing_number
    jnl_filing_4_filing_type_desc
    jnl_filing_4_filing_date
    jnl_filing_4_filing_time
    jnl_filing_4_filing_book
    jnl_filing_4_filing_page
    jnl_filing_4_agency
    jnl_filing_4_agency_state
    jnl_filing_4_agency_city
    jnl_filing_4_agency_county
  }
}
CriminalRecords {
  CriminalRecord {
    crim_FullName
    crim_lname
    crim_fname
    crim_mname
    crim_pty_typ
    crim_citizenship
    crim_dle_num
    crim_fbi_num
    crim_ins_num
    crim_id_num
    crim_doc_num
    crim_dob
    crim_dob_alias
    crim_place_of_birth
    crim_street_address_1
    crim_street_address_2
    crim_street_address_3
    crim_street_address_4
    crim_street_address_5
    crim_curr_incar_flag
    crim_curr_parole_flag
    crim_curr_probation_flag
    crim_race
    crim_race_desc
    crim_sex
    crim_hair_color
    crim_hair_color_desc
    crim_eye_color
    crim_eye_color_desc
    crim_skin_color
    crim_skin_color_desc
    crim_height
    crim_weight
    crim_party_status
    crim_party_status_desc
    crim_data_type
    crim_datasource
    crim_Address
    crim_City
    crim_State
    crim_Zip
    crim_process_date
    crim_case_num_1
    crim_off_date_1
    crim_arr_date_1
    crim_num_of_counts_1
    crim_off_code_1
    crim_chg_1
    crim_off_desc_1_1
    crim_off_desc_2_1
    crim_add_off_cd_1
    crim_add_off_desc_1
    crim_off_typ_1
    crim_off_lev_1
    crim_court_desc_1
    crim_cty_conv_1
    crim_stc_dt_1
    crim_stc_comp_1
    crim_stc_desc_1_1
    crim_stc_desc_2_1
    crim_stc_desc_3_1
    crim_stc_desc_4_1
    crim_stc_lgth_1
    crim_stc_lgth_desc_1
    crim_inc_adm_dt_1
    crim_min_term_1
    crim_min_term_desc_1
    crim_max_term_1
    crim_max_term_desc_1
    crim_case_num_2
    crim_off_date_2
    crim_arr_date_2
    crim_num_of_counts_2
    crim_off_code_2
    crim_chg_2
    crim_off_desc_1_2
    crim_off_desc_2_2
    crim_add_off_cd_2
    crim_add_off_desc_2
    crim_off_typ_2
    crim_off_lev_2
    crim_court_desc_2
    crim_cty_conv_2
    crim_stc_dt_2
    crim_stc_comp_2
    crim_stc_desc_1_2
    crim_stc_desc_2_2
    crim_stc_desc_3_2
    crim_stc_desc_4_2
    crim_stc_lgth_2
    crim_stc_lgth_desc_2
    crim_inc_adm_dt_2
    crim_min_term_2
    crim_min_term_desc_2
    crim_max_term_2
    crim_max_term_desc_2
    crim_case_num_3
    crim_off_date_3
    crim_arr_date_3
    crim_num_of_counts_3
    crim_off_code_3
    crim_chg_3
    crim_off_desc_1_3
    crim_off_desc_2_3
    crim_add_off_cd_3
    crim_add_off_desc_3
    crim_off_typ_3
    crim_off_lev_3
    crim_court_desc_3
    crim_cty_conv_3
    crim_stc_dt_3
    crim_stc_comp_3
    crim_stc_desc_1_3
    crim_stc_desc_2_3
    crim_stc_desc_3_3
    crim_stc_desc_4_3
    crim_stc_lgth_3
    crim_stc_lgth_desc_3
    crim_inc_adm_dt_3
    crim_min_term_3
    crim_min_term_desc_3
    crim_max_term_3
    crim_max_term_desc_3
    crim_case_num_4
    crim_off_date_4
    crim_arr_date_4
    crim_num_of_counts_4
    crim_off_code_4
    crim_chg_4
    crim_off_desc_1_4
    crim_off_desc_2_4
    crim_add_off_cd_4
    crim_add_off_desc_4
    crim_off_typ_4
    crim_off_lev_4
    crim_court_desc_4
    crim_cty_conv_4
    crim_stc_dt_4
    crim_stc_comp_4
    crim_stc_desc_1_4
    crim_stc_desc_2_4
    crim_stc_desc_3_4
    crim_stc_desc_4_4
    crim_stc_lgth_4
    crim_stc_lgth_desc_4
    crim_inc_adm_dt_4
    crim_min_term_4
    crim_min_term_desc_4
    crim_max_term_4
    crim_max_term_desc_4
    crim_case_num_5
    crim_off_date_5
    crim_arr_date_5
    crim_num_of_counts_5
    crim_off_code_5
    crim_chg_5
    crim_off_desc_1_5
    crim_off_desc_2_5
    crim_add_off_cd_5
    crim_add_off_desc_5
    crim_off_typ_5
    crim_off_lev_5
    crim_court_desc_5
    crim_cty_conv_5
    crim_stc_dt_5
    crim_stc_comp_5
    crim_stc_desc_1_5
    crim_stc_desc_2_5
    crim_stc_desc_3_5
    crim_stc_desc_4_5
    crim_stc_lgth_5
    crim_stc_lgth_desc_5
    crim_inc_adm_dt_5
    crim_min_term_5
    crim_min_term_desc_5
    crim_max_term_5
    crim_max_term_desc_5
    crim_case_num_6
    crim_off_date_6
    crim_arr_date_6
    crim_num_of_counts_6
    crim_off_code_6
    crim_chg_6
    crim_off_desc_1_6
    crim_off_desc_2_6
    crim_add_off_cd_6
    crim_add_off_desc_6
    crim_off_typ_6
    crim_off_lev_6
    crim_court_desc_6
    crim_cty_conv_6
    crim_stc_dt_6
    crim_stc_comp_6
    crim_stc_desc_1_6
    crim_stc_desc_2_6
    crim_stc_desc_3_6
    crim_stc_desc_4_6
    crim_stc_lgth_6
    crim_stc_lgth_desc_6
    crim_inc_adm_dt_6
    crim_min_term_6
    crim_min_term_desc_6
    crim_max_term_6
    crim_max_term_desc_6
    crim_par_event_dt_1
    crim_presump_par_rel_desc_1
    crim_par_cur_stat_1
    crim_par_cur_stat_desc_1
    crim_par_st_dt_1
    crim_par_sch_end_dt_1
    crim_par_act_end_dt_1
    crim_par_cty_1
    crim_par_event_dt_2
    crim_presump_par_rel_desc_2
    crim_par_cur_stat_2
    crim_par_cur_stat_desc_2
    crim_par_st_dt_2
    crim_par_sch_end_dt_2
    crim_par_act_end_dt_2
    crim_par_cty_2
    crim_par_event_dt_3
    crim_presump_par_rel_desc_3
    crim_par_cur_stat_3
    crim_par_cur_stat_desc_3
    crim_par_st_dt_3
    crim_par_sch_end_dt_3
    crim_par_act_end_dt_3
    crim_par_cty_3
    crim_par_event_dt_4
    crim_presump_par_rel_desc_4
    crim_par_cur_stat_4
    crim_par_cur_stat_desc_4
    crim_par_st_dt_4
    crim_par_sch_end_dt_4
    crim_par_act_end_dt_4
    crim_par_cty_4
    crim_par_event_dt_5
    crim_presump_par_rel_desc_5
    crim_par_cur_stat_5
    crim_par_cur_stat_desc_5
    crim_par_st_dt_5
    crim_par_sch_end_dt_5
    crim_par_act_end_dt_5
    crim_par_cty_5
    crim_par_event_dt_6
    crim_presump_par_rel_desc_6
    crim_par_cur_stat_6
    crim_par_cur_stat_desc_6
    crim_par_st_dt_6
    crim_par_sch_end_dt_6
    crim_par_act_end_dt_6
    crim_par_cty_6
    crim_in_event_dt_1
    crim_sent_length_1
    crim_sent_length_desc_1
    crim_cur_stat_inm_1
    crim_cur_stat_inm_desc_1
    crim_cur_loc_inm_cd_1
    crim_cur_loc_inm_1
    crim_cur_sec_class_dt_1
    crim_cur_loc_sec_1
    crim_gain_time_1
    crim_gain_time_eff_dt_1
    crim_latest_adm_dt_1
    crim_sch_rel_dt_1
    crim_act_rel_dt_1
    crim_ctl_rel_dt_1
    crim_in_event_dt_2
    crim_sent_length_2
    crim_sent_length_desc_2
    crim_cur_stat_inm_2
    crim_cur_stat_inm_desc_2
    crim_cur_loc_inm_cd_2
    crim_cur_loc_inm_2
    crim_cur_sec_class_dt_2
    crim_cur_loc_sec_2
    crim_gain_time_2
    crim_gain_time_eff_dt_2
    crim_latest_adm_dt_2
    crim_sch_rel_dt_2
    crim_act_rel_dt_2
    crim_ctl_rel_dt_2
    crim_in_event_dt_3
    crim_sent_length_3
    crim_sent_length_desc_3
    crim_cur_stat_inm_3
    crim_cur_stat_inm_desc_3
    crim_cur_loc_inm_cd_3
    crim_cur_loc_inm_3
    crim_cur_sec_class_dt_3
    crim_cur_loc_sec_3
    crim_gain_time_3
    crim_gain_time_eff_dt_3
    crim_latest_adm_dt_3
    crim_sch_rel_dt_3
    crim_act_rel_dt_3
    crim_ctl_rel_dt_3
    crim_in_event_dt_4
    crim_sent_length_4
    crim_sent_length_desc_4
    crim_cur_stat_inm_4
    crim_cur_stat_inm_desc_4
    crim_cur_loc_inm_cd_4
    crim_cur_loc_inm_4
    crim_cur_sec_class_dt_4
    crim_cur_loc_sec_4
    crim_gain_time_4
    crim_gain_time_eff_dt_4
    crim_latest_adm_dt_4
    crim_sch_rel_dt_4
    crim_act_rel_dt_4
    crim_ctl_rel_dt_4
    crim_in_event_dt_5
    crim_sent_length_5
    crim_sent_length_desc_5
    crim_cur_stat_inm_5
    crim_cur_stat_inm_desc_5
    crim_cur_loc_inm_cd_5
    crim_cur_loc_inm_5
    crim_cur_sec_class_dt_5
    crim_cur_loc_sec_5
    crim_gain_time_5
    crim_gain_time_eff_dt_5
    crim_latest_adm_dt_5
    crim_sch_rel_dt_5
    crim_act_rel_dt_5
    crim_ctl_rel_dt_5
    crim_in_event_dt_6
    crim_sent_length_6
    crim_sent_length_desc_6
    crim_cur_stat_inm_6
    crim_cur_stat_inm_desc_6
    crim_cur_loc_inm_cd_6
    crim_cur_loc_inm_6
    crim_cur_sec_class_dt_6
    crim_cur_loc_sec_6
    crim_gain_time_6
    crim_gain_time_eff_dt_6
    crim_latest_adm_dt_6
    crim_sch_rel_dt_6
    crim_act_rel_dt_6
    crim_ctl_rel_dt_6
  }
}
SexOffenderRecords {
  SexOffenderRecord {
    sof_last_name
    sof_first_name
    sof_middle_name
    sof_name_suffix
    sof_address_1
    sof_address_2
    sof_address_3
    sof_date_last_seen
    sof_sex
    sof_dob
    sof_hair_color
    sof_eye_color
    sof_scars
    sof_height
    sof_weight
    sof_race
    sof_offender_id
    sof_state_of_origin
    sof_offense_1
    sof_conviction_place_1
    sof_conviction_date_1
    sof_victim_minor_1
    sof_conviction_jurisdiction_1
    sof_court_case_number_1
    sof_offense_date_1
    sof_offense_2
    sof_conviction_place_2
    sof_conviction_date_2
    sof_victim_minor_2
    sof_conviction_jurisdiction_2
    sof_court_case_number_2
    sof_offense_date_2
    sof_offense_3
    sof_conviction_place_3
    sof_conviction_date_3
    sof_victim_minor_3
    sof_conviction_jurisdiction_3
    sof_court_case_number_3
    sof_offense_date_3
    sof_offense_4
    sof_conviction_place_4
    sof_conviction_date_4
    sof_victim_minor_4
    sof_conviction_jurisdiction_4
    sof_court_case_number_4
    sof_offense_date_4
    sof_offense_5
    sof_conviction_place_5
    sof_conviction_date_5
    sof_victim_minor_5
    sof_conviction_jurisdiction_5
    sof_court_case_number_5
    sof_offense_date_5
    sof_offense_6
    sof_conviction_place_6
    sof_conviction_date_6
    sof_victim_minor_6
    sof_conviction_jurisdiction_6
    sof_court_case_number_6
    sof_offense_date_6
    sof_offense_7
    sof_conviction_place_7
    sof_conviction_date_7
    sof_victim_minor_7
    sof_conviction_jurisdiction_7
    sof_court_case_number_7
    sof_offense_date_7
    sof_offense_8
    sof_conviction_place_8
    sof_conviction_date_8
    sof_victim_minor_8
    sof_conviction_jurisdiction_8
    sof_court_case_number_8
    sof_offense_date_8
    sof_offense_9
    sof_conviction_place_9
    sof_conviction_date_9
    sof_victim_minor_9
    sof_conviction_jurisdiction_9
    sof_court_case_number_9
    sof_offense_date_9
    sof_offense_10
    sof_conviction_place_10
    sof_conviction_date_10
    sof_victim_minor_10
    sof_conviction_jurisdiction_10
    sof_court_case_number_10
    sof_offense_date_10
    sof_curr_incar_flag
    sof_curr_parole_flag
    sof_curr_probation_flag
    sof_doc_number
    sof_registration_county
    sof_Address
    sof_City
    sof_State
    sof_Zip
  }
}
PropertyRecords {
  PropertyRecord {
    deed_state
    deed_county_name
    deed_apnt_or_pin_number
    deed_fips_code
    deed_record_type
    deed_record_type_desc
    deed_multi_apn_flag
    deed_buyer_addendum_flag
    deed_seller_addendum_flag
    deed_lender_name
    deed_lender_name_id
    deed_lender_dba_aka_name
    deed_tax_id_number
    deed_phone_number
    deed_property_address_code
    deed_property_address_desc
    deed_lender_full_street_address
    deed_lender_address_unit_number
    deed_lender_address_citystatezip
    deed_legal_brief_description
    deed_contract_date
    deed_recording_date
    deed_document_type_code
    deed_document_type_desc
    deed_arm_reset_date
    deed_document_number
    deed_recorder_book_number
    deed_recorder_page_number
    deed_land_lot_size
    deed_legal_lot_desc
    deed_legal_lot_number
    deed_legal_block
    deed_legal_section
    deed_legal_district
    deed_legal_land_lot
    deed_legal_unit
    deed_legal_city_municipality_township
    deed_legal_subdivision_name
    deed_legal_phase_number
    deed_legal_tract_number
    deed_legal_sec_twn_rng_mer
    deed_recorder_map_reference
    deed_complete_legal_description_code
    deed_loan_number
    deed_concurrent_mortgage_book_page_document_number
    deed_hawaii_tct
    deed_hawaii_condo_cpr_code
    deed_hawaii_condo_name
    deed_filler_except_hawaii
    deed_sales_price
    deed_sales_price_desc
    deed_city_transfer_tax
    deed_county_transfer_tax
    deed_total_transfer_tax
    deed_excise_tax_number
    deed_property_use_desc
    deed_assessment_match_land_use_desc
    deed_condo_desc
    deed_timeshare_flag
    deed_first_td_loan_amount
    deed_first_td_loan_type_desc
    deed_type_financing
    deed_type_financing_desc
    deed_first_td_interest_rate
    deed_first_td_due_date
    deed_title_company_name
    deed_rate_change_frequency
    deed_rate_change_frequency_desc
    deed_change_index
    deed_adjustable_rate_index
    deed_adjustable_rate_index_desc
    deed_adjustable_rate_rider
    deed_graduated_payment_rider
    deed_balloon_rider
    deed_fixed_step_rate_rider
    deed_fixed_step_rate_rider_desc
    deed_condominium_rider
    deed_planned_unit_development_rider
    deed_rate_improvement_rider
    deed_assumability_rider
    deed_prepayment_rider
    deed_one_four_family_rider
    deed_biweekly_payment_rider
    deed_second_home_rider
    deed_second_td_loan_amount
    deed_first_td_lender_type_desc
    deed_second_td_lender_type_desc
    deed_partial_interest_transferred
    deed_loan_term_months
    deed_loan_term_years
    deed_transaction_type_desc
    deed_mortgage_deed_type_desc
    deed_mortgage_term_code_desc
    deed_mortgage_term
    deed_iris_apn
    deed_lender_address
    deed_mortgage_date
    deed_building_square_feet
    deed_foreclosure_desc
    deed_refi_flag_desc
    deed_equity_flag_desc
    assess_state_code
    assess_county_name
    assess_apna_or_pin_number
    assess_fips_code
    assess_duplicate_apn_multiple_address_id
    assess_tape_cut_date
    assess_edition_number
    assess_certification_date
    assess_assessee_ownership_rights_desc
    assess_assessee_relationship_desc
    assess_assessee_phone_number
    assess_tax_account_number
    assess_contract_owner
    assess_assessee_name_type_desc
    assess_second_assessee_name_type_desc
    assess_mail_care_of_name_type_desc
    assess_mailing_care_of_name
    assess_property_address_desc
    assess_owner_occupied
    assess_recording_date
    assess_prior_recording_date
    assess_county_land_use_description
    assess_standardized_land_use_desc
    assess_legal_lot_number
    assess_legal_subdivision_name
    assess_legal_brief_description
    assess_record_type_desc
    assess_recorder_book_number
    assess_recorder_page_number
    assess_legal_lot_desc
    assess_legal_land_lot
    assess_legal_block
    assess_legal_section
    assess_legal_district
    assess_legal_unit
    assess_legal_city_municipality_township
    assess_legal_phase_number
    assess_legal_tract_number
    assess_legal_sec_twn_rng_mer
    assess_legal_assessor_map_ref
    assess_census_tract
    assess_ownership_type_desc
    assess_new_record_type_desc
    assess_timeshare_code
    assess_zoning
    assess_recorder_document_number
    assess_transfer_date
    assess_document_type
    assess_document_type_desc
    assess_prior_transfer_date
    assess_sale_date
    assess_sales_price
    assess_sales_price_desc
    assess_prior_sales_price
    assess_prior_sales_price_desc
    assess_mortgage_loan_amount
    assess_mortgage_loan_type_desc
    assess_mortgage_lender_name
    assess_mortgage_lender_type_desc
    assess_assessed_total_value
    assess_assessed_value_year
    assess_homestead_homeowner_exemption
    assess_assessed_improvement_value
    assess_market_land_value
    assess_market_improvement_value
    assess_market_total_value
    assess_market_value_year
    assess_assessed_land_value
    assess_tax_year
    assess_tax_amount
    assess_tax_exemption1_desc
    assess_tax_exemption2_desc
    assess_tax_exemption3_desc
    assess_tax_exemption4_desc
    assess_tax_rate_code_area
    assess_tax_delinquent_year
    assess_school_tax_district1
    assess_school_tax_district2
    assess_school_tax_district3
    assess_land_square_footage
    assess_year_built
    assess_no_of_stories
    assess_no_of_stories_desc
    assess_no_of_bedrooms
    assess_no_of_baths
    assess_no_of_partial_baths
    assess_garage_type_desc
    assess_pool_desc
    assess_exterior_walls_desc
    assess_roof_type_desc
    assess_heating_desc
    assess_heating_fuel_type_desc
    assess_air_conditioning_desc
    assess_air_conditioning_type_desc
    assess_land_acres
    assess_land_dimensions
    assess_building_area
    assess_building_area1
    assess_building_area2
    assess_building_area3
    assess_building_area4
    assess_building_area5
    assess_building_area6
    assess_building_area7
    assess_building_area_desc
    assess_building_area1_desc
    assess_building_area2_desc
    assess_building_area3_desc
    assess_building_area4_desc
    assess_building_area5_desc
    assess_building_area6_desc
    assess_building_area7_desc
    assess_effective_year_built
    assess_no_of_buildings
    assess_no_of_units
    assess_no_of_rooms
    assess_parking_no_of_cars
    assess_style_desc
    assess_type_construction_desc
    assess_foundation_desc
    assess_roof_cover_desc
    assess_elevator
    assess_fireplace_indicator_desc
    assess_fireplace_number
    assess_basement_desc
    assess_building_class_desc
    assess_site_influence1_desc
    assess_site_influence2_desc
    assess_site_influence3_desc
    assess_site_influence4_desc
    assess_site_influence5_desc
    assess_amenities1_desc
    assess_amenities2_desc
    assess_amenities3_desc
    assess_amenities4_desc
    assess_amenities5_desc
    assess_other_buildings1_desc
    assess_other_buildings2_desc
    assess_other_buildings3_desc
    assess_other_buildings4_desc
    assess_other_buildings5_desc
    assess_condo_project_name
    assess_building_name
    assess_comments
    assess_neighborhood_code
    assess_living_square_feet
    assess_iris_apn
    assess_addl_legal
    assess_calculated_land_value
    assess_calculated_improvement_value
    assess_calculated_total_value
    assess_adjusted_gross_square_feet
    assess_no_of_full_baths
    assess_no_of_half_baths
    assess_pool_indicator
    assess_frame_desc
    assess_electric_energy_desc
    assess_sewer_desc
    assess_water_desc
    assess_condition_desc
    property_address1
    property_address2
    property_p_city_name
    property_v_city_name
    property_st
    property_zip
    property_zip4
    property_county_name
    property_geo_lat
    property_geo_long
    property_msa
    property_orig_address
    property_orig_unit
    property_orig_csz
    buyer_address1
    buyer_address2
    buyer_p_city_name
    buyer_v_city_name
    buyer_st
    buyer_zip
    buyer_zip4
    buyer_county_name
    buyer_geo_lat
    buyer_geo_long
    buyer_msa
    buyer_orig_address
    buyer_orig_unit
    buyer_orig_csz
    buyer_phone_number
    buyer_vesting_desc
    buyer_1_orig_name
    buyer_1_id_desc
    buyer_1_title
    buyer_1_first_name
    buyer_1_middle_name
    buyer_1_last_name
    buyer_1_name_suffix
    buyer_1_company_name
    buyer_1_did
    buyer_1_bdid
    buyer_1_ssn
    buyer_2_orig_name
    buyer_2_id_desc
    buyer_2_title
    buyer_2_first_name
    buyer_2_middle_name
    buyer_2_last_name
    buyer_2_name_suffix
    buyer_2_company_name
    buyer_2_did
    buyer_2_bdid
    buyer_2_ssn
    seller_address1
    seller_address2
    seller_p_city_name
    seller_v_city_name
    seller_st
    seller_zip
    seller_zip4
    seller_county_name
    seller_geo_lat
    seller_geo_long
    seller_msa
    seller_orig_address
    seller_orig_unit
    seller_orig_csz
    seller_phone_number
    seller_1_orig_name
    seller_1_id_desc
    seller_1_title
    seller_1_first_name
    seller_1_middle_name
    seller_1_last_name
    seller_1_name_suffix
    seller_1_company_name
    seller_1_did
    seller_1_bdid
    seller_1_ssn
    seller_2_orig_name
    seller_2_id_desc
    seller_2_title
    seller_2_first_name
    seller_2_middle_name
    seller_2_last_name
    seller_2_name_suffix
    seller_2_company_name
    seller_2_did
    seller_2_bdid
    seller_2_ssn
    owner_address1
    owner_address2
    owner_p_city_name
    owner_v_city_name
    owner_st
    owner_zip
    owner_zip4
    owner_county_name
    owner_geo_lat
    owner_geo_long
    owner_msa
    owner_orig_address
    owner_orig_unit
    owner_orig_csz
    owner_phone_number
    owner_1_orig_name
    owner_1_title
    owner_1_first_name
    owner_1_middle_name
    owner_1_last_name
    owner_1_name_suffix
    owner_1_company_name
    owner_1_did
    owner_1_bdid
    owner_1_ssn
    owner_2_orig_name
    owner_2_title
    owner_2_first_name
    owner_2_middle_name
    owner_2_last_name
    owner_2_name_suffix
    owner_2_company_name
    owner_2_did
    owner_2_bdid
    owner_2_ssn
    assessee_address1
    assessee_address2
    assessee_p_city_name
    assessee_v_city_name
    assessee_st
    assessee_zip
    assessee_zip4
    assessee_county_name
    assessee_geo_lat
    assessee_geo_long
    assessee_msa
    assessee_orig_address
    assessee_orig_unit
    assessee_orig_csz
    assessee_phone_number
    assessee_1_orig_name
    assessee_1_title
    assessee_1_first_name
    assessee_1_middle_name
    assessee_1_last_name
    assessee_1_name_suffix
    assessee_1_company_name
    assessee_1_did
    assessee_1_bdid
    assessee_1_ssn
    assessee_2_orig_name
    assessee_2_title
    assessee_2_first_name
    assessee_2_middle_name
    assessee_2_last_name
    assessee_2_name_suffix
    assessee_2_company_name
    assessee_2_did
    assessee_2_bdid
    assessee_2_ssn
    borrower_address1
    borrower_address2
    borrower_p_city_name
    borrower_v_city_name
    borrower_st
    borrower_zip
    borrower_zip4
    borrower_county_name
    borrower_geo_lat
    borrower_geo_long
    borrower_msa
    borrower_orig_address
    borrower_orig_unit
    borrower_orig_csz
    borrower_phone_number
    borrower_vesting_desc
    borrower_1_orig_name
    borrower_1_id_desc
    borrower_1_title
    borrower_1_first_name
    borrower_1_middle_name
    borrower_1_last_name
    borrower_1_name_suffix
    borrower_1_company_name
    borrower_1_did
    borrower_1_bdid
    borrower_1_ssn
    borrower_2_orig_name
    borrower_2_id_desc
    borrower_2_title
    borrower_2_first_name
    borrower_2_middle_name
    borrower_2_last_name
    borrower_2_name_suffix
    borrower_2_company_name
    borrower_2_did
    borrower_2_bdid
    borrower_2_ssn
  }
}
ForeclosureRecords {
  ForeclosureRecord {
    pfc_geo_lat
    pfc_geo_long
    pfc_geo_blk
    pfc_dms_lat
    pfc_dms_long
    pfc_county
    pfc_msa
    pfc_geo_match
    pfc_geolink
    pfc_vacancy_ind
    pfc_vac_begdt
    pfc_fc_unique_id
    pfc_fc_ind
    pfc_fc_addr_ind
    pfc_owner_type
    pfc_cp_data_datee
    pfc_foreclosure_stage
    pfc_deed_event_type_cd
    pfc_deed_event_type_desc
    pfc_doc_type_cd
    pfc_doc_type_desc
    pfc_cp_sale_amt
    pfc_cp_dflt_amt
    pfc_cp_dflt_dt
    pfc_cp_auction_dt
    pfc_lndr_cmpny_name
    pfc_property_type_cd
    pfc_property_type_desc
    pfc_ownr_1_first_name
    pfc_ownr_1_last_name
    pfc_ownr_1_cmpny_name
    pfc_ownr_2_first_name
    pfc_ownr_2_last_name
    pfc_ownr_3_first_name
    pfc_ownr_3_last_name
    pfc_ownr_4_first_name
    pfc_ownr_4_last_name
    pfc_cp_filing_dt
    pfc_cp_recording_dt
    pfc_subdv_name
    pfc_court_case_nbr
    pfc_plntff1_name
    pfc_plntff2_name
    pfc_trustee_name
    pfc_trustee_addr
    pfc_trustee_city
    pfc_trustee_state
    pfc_trustee_zipcd
    pfc_trustee_phone_nbr
    pfc_orig_loan_dt
    pfc_orig_loan_recording_dt
    pfc_last_fullsale_trnsfr_dt
    pfc_expand_legal_desc
    pfc_legal_desc_2
    pfc_legal_desc_3
    pfc_legal_desc_4
    pfc_PropertyAddress
    pfc_PropertyCity
    pfc_PropertyState
    pfc_PropertyZip
    pfc_FullProperty
    pfc_parcel_number_parcel_id
    pfc_parcel_number_unmatched_id
    pfc_foreclosure_type_flag
    pfc_deed_document_type_desc
    pfc_date_file_processed
    pfc_deed_recording_date
    pfc_foreclosure_type_age_flag
    pfc_prim_range_pfc
    pfc_predir_pfc
    pfc_prim_name_pfc
    pfc_suffix_pfc
    pfc_postdir_pfc
    pfc_unit_desig_pfc
    pfc_sec_range_pfc
    pfc_p_city_name_pfc
    pfc_st_pfc
    pfc_zip_pfc
    pfc_zip4_pfc
  }
}
ProfessionalLicenseRecords {
  ProfessionalLicenseRecord {
      pro_uniqueid
      pro_npi
      pro_prolic_seq_id
      pro_ProviderId
      pro_sanc_id
      pro_DEANumber
      pro_taxid
      pro_orig_license_number
      pro_status
      pro_orig_name
      pro_orig_former_name
      pro_company_name
      pro_orig_addr_1
      pro_orig_addr_2
      pro_orig_city
      pro_orig_st
      pro_orig_zip
      pro_additional_orig_name
      pro_additional_orig_additional_1
      pro_additional_orig_additional_2
      pro_additional_orig_city
      pro_additional_orig_st
      pro_additional_orig_zip
      pro_did
      pro_bdid
      pro_phone
      pro_Phonetype
      pro_sex
      pro_dob
      pro_best_ssn
      pro_issue_date
      pro_expiration_date
      pro_status_effective_dt
      pro_action_status
      pro_date_last_seen
      pro_last_renewal_date
      pro_profession_or_board
      pro_license_type
      pro_license_obtained_by
      pro_source_st
      pro_source_st_decoded
      pro_Address
      pro_City
      pro_State
      pro_ZipCode
      pro_title
      pro_fname
      pro_mname
      pro_lname
      pro_name_suffix
      pro_county_name
      pro_license_number
      pro_board_action_indicator
      pro_action_complaint_violation_dt
      pro_action_complaint_violation_desc
      pro_action_case_number
      pro_action_desc
      pro_action_posting_status_dt
      pro_action_effective_dt
      pro_misc_other_id
      pro_education_continuing_education
      pro_education_1_school_attended
      pro_education_1_dates_attended
      pro_education_1_curriculum
      pro_education_1_degree
      pro_education_2_school_attended
      pro_education_2_dates_attended
      pro_education_2_curriculum
      pro_education_2_degree
      pro_education_3_school_attended
      pro_education_3_dates_attended
      pro_education_3_curriculum
      pro_education_3_degree
      pro_business_flag
      pro_misc_fax
      pro_misc_email
      pro_additional_phone
      pro_personal_race_desc
      pro_misc_occupation
      pro_action_record_type
      pro_personal_pob_desc
      pro_other_license_number
      pro_other_license_type
      pro_misc_practice_hours
      pro_misc_practice_type
      pro_additional_licensing_specifics
      pro_expired_flag
  }
}
EmailAddressRecords {
  EmailAddressRecord {
    eml_fname
    eml_mname
    eml_lname
    eml_name_suffix
    eml_company_title
    eml_cln_company_name
    eml_address
    eml_city
    eml_st
    eml_zip
    eml_orig_email
    eml_clean_email
    eml_best_fname
    eml_best_mname
    eml_best_lname
    eml_best_name_suffix
    eml_best_address
    eml_best_city
    eml_best_st
    eml_best_zip
    eml_date_first_seen
    eml_date_last_seen
    eml_email_status
    eml_email_status_reason
    eml_additional_status_info
    eml_relationship
  }
}
PhoneRecords {
  PhoneRecord {
    subj_first
    subj_middle
    subj_last
    subj_suffix
    subj_phone
    subj_phone_listing_name
    subj_phone_possible_relationship
    subj_date_first_seen
    subj_date_last_seen
    subj_phone_type
    subj_phone_carrier
    subj_phone_carrier_city
    subj_phone_carrier_state
    subj_phone_search_level_code
    subj_phone_duplicate_to_input_flag
    subj_phone_line_type
    subj_phone_possible_timezone
    subj_phone_address_zipcode_timezone
    subj_timezone_match_flag
    subj_phone_ported_date
    subj_phone_seen_freq
    subj_phone_age
    subj_phone_match_code
    subj_phone_transient_flag
  }
}
PeopleAtWorkRecords {
  PeopleAtWorkRecord {
    pawk_1_did
    pawk_1_confidence_level
    pawk_1_first
    pawk_1_middle
    pawk_1_last
    pawk_1_suffix
    pawk_1_ssn
    pawk_1_title
    pawk_1_first_seen
    pawk_1_last_seen
    pawk_1_bdid
    pawk_1_company_name
    pawk_1_department
    pawk_1_fein
    pawk_1_address
    pawk_1_city
    pawk_1_state
    pawk_1_zip5
    pawk_1_zip4
    pawk_1_phone10
    pawk_1_verified
    pawk_1_email
    pawk_2_did
    pawk_2_confidence_level
    pawk_2_first
    pawk_2_middle
    pawk_2_last
    pawk_2_suffix
    pawk_2_ssn
    pawk_2_title
    pawk_2_first_seen
    pawk_2_last_seen
    pawk_2_bdid
    pawk_2_company_name
    pawk_2_department
    pawk_2_fein
    pawk_2_address
    pawk_2_city
    pawk_2_state
    pawk_2_zip5
    pawk_2_zip4
    pawk_2_phone10
    pawk_2_verified
    pawk_2_email
    pawk_3_did
    pawk_3_confidence_level
    pawk_3_first
    pawk_3_middle
    pawk_3_last
    pawk_3_suffix
    pawk_3_ssn
    pawk_3_title
    pawk_3_first_seen
    pawk_3_last_seen
    pawk_3_bdid
    pawk_3_company_name
    pawk_3_department
    pawk_3_fein
    pawk_3_address
    pawk_3_city
    pawk_3_state
    pawk_3_zip5
    pawk_3_zip4
    pawk_3_phone10
    pawk_3_verified
    pawk_3_email
    pawk_4_did
    pawk_4_confidence_level
    pawk_4_first
    pawk_4_middle
    pawk_4_last
    pawk_4_suffix
    pawk_4_ssn
    pawk_4_title
    pawk_4_first_seen
    pawk_4_last_seen
    pawk_4_bdid
    pawk_4_company_name
    pawk_4_department
    pawk_4_fein
    pawk_4_address
    pawk_4_city
    pawk_4_state
    pawk_4_zip5
    pawk_4_zip4
    pawk_4_phone10
    pawk_4_verified
    pawk_4_email
    pawk_5_did
    pawk_5_confidence_level
    pawk_5_first
    pawk_5_middle
    pawk_5_last
    pawk_5_suffix
    pawk_5_ssn
    pawk_5_title
    pawk_5_first_seen
    pawk_5_last_seen
    pawk_5_bdid
    pawk_5_company_name
    pawk_5_department
    pawk_5_fein
    pawk_5_address
    pawk_5_city
    pawk_5_state
    pawk_5_zip5
    pawk_5_zip4
    pawk_5_phone10
    pawk_5_verified
    pawk_5_email
  }
}
WatercraftRecords {
  WatercraftRecord {
    boat_watercraft_key
    boat_sequence_key
    boat_state_origin
    boat_watercraft_id
    boat_source_code
    boat_watercraft_name
    boat_hull_number
    boat_hull_type_code
    boat_hull_type_description
    boat_watercraft_length
    boat_watercraft_width
    boat_watercraft_weight
    boat_watercraft_class_code
    boat_watercraft_class_description
    boat_watercraft_make_code
    boat_watercraft_make_description
    boat_watercraft_model_code
    boat_watercraft_model_description
    boat_watercraft_color_1_code
    boat_watercraft_color_1_description
    boat_watercraft_color_2_code
    boat_watercraft_color_2_description
    boat_model_year
    boat_use_code
    boat_use_description
    boat_propulsion_code
    boat_propulsion_description
    boat_fuel_code
    boat_fuel_description
    boat_title_state
    boat_title_status_code
    boat_title_status_description
    boat_title_number
    boat_title_type_code
    boat_title_type_description
    boat_title_issue_date
    boat_state_purchased
    boat_purchase_date
    boat_purchase_price
    boat_dealer
    boat_new_used_flag
    boat_st_registration
    boat_county_registration
    boat_registration_status_date
    boat_registration_renewal_date
    boat_decal_number
    boat_transaction_type_code
    boat_transaction_type_description
    boat_watercraft_toilet_description
    boat_signatory
    boat_vehicle_type_code
    boat_vehicle_type_description
    boat_watercraft_number_of_engines
    boat_coast_guard_documented_flag
    boat_coast_guard_number
    boat_registered_breadth
    boat_registered_depth
    boat_registered_gross_tons
    boat_registered_net_tons
    boat_registration_status_code
    boat_registration_status_description
    boat_registration_number
    boat_registration_date
    boat_registration_expiration_date
    boat_main_hp_ahead
    boat_main_hp_astern
    boat_hailing_port
    boat_hailing_port_state
    boat_hailing_port_province
    boat_vessel_build_year
    boat_vessel_complete_build_city
    boat_vessel_complete_build_state
    boat_vessel_complete_build_province
    boat_vessel_complete_build_country
    boat_vessel_hull_build_city
    boat_vessel_hull_build_state
    boat_vessel_hull_build_province
    boat_vessel_hull_build_country
    boat_vessel_id
    boat_vessel_database_key
    boat_call_sign
    boat_imo_number
    boat_party_identification_number
    boat_itc_gross_tons
    boat_itc_net_tons
    boat_itc_length
    boat_itc_breadth
    boat_itc_depth
    boat_home_port_name
    boat_home_port_state
    boat_home_port_province
    boat_engine_1_number
    boat_engine_1_make
    boat_engine_1_model
    boat_engine_1_year
    boat_watercraft_hp_1
    boat_engine_2_number
    boat_engine_2_make
    boat_engine_2_model
    boat_engine_2_year
    boat_watercraft_hp_2
    boat_engine_3_number
    boat_engine_3_make
    boat_engine_3_model
    boat_engine_3_year
    boat_watercraft_hp_3
    boat_did_1
    boat_bdid_1
    boat_ultid_1
    boat_orgid_1
    boat_seleid_1
    boat_proxid_1
    boat_powid_1
    boat_empid_1
    boat_dotid_1
    boat_orig_name_1
    boat_orig_name_type_code_1
    boat_orig_name_type_description_1
    boat_orig_name_first_1
    boat_orig_name_middle_1
    boat_orig_name_last_1
    boat_orig_address_1_1
    boat_orig_address_2_1
    boat_orig_fips_1
    boat_orig_province_1
    boat_orig_country_1
    boat_dob_1
    boat_orig_ssn_1
    boat_orig_fein_1
    boat_gender_1
    boat_phone_1_1
    boat_phone_2_1
    boat_title_1
    boat_fname_1
    boat_mname_1
    boat_lname_1
    boat_name_suffix_1
    boat_company_name_1
    boat_prim_range_1
    boat_predir_1
    boat_prim_name_1
    boat_suffix_1
    boat_postdir_1
    boat_unit_desig_1
    boat_sec_range_1
    boat_p_city_name_1
    boat_v_city_name_1
    boat_st_1
    boat_zip5_1
    boat_zip4_1
    boat_county_1
    boat_did_2
    boat_bdid_2
    boat_ultid_2
    boat_orgid_2
    boat_seleid_2
    boat_proxid_2
    boat_powid_2
    boat_empid_2
    boat_dotid_2
    boat_orig_name_2
    boat_orig_name_type_code_2
    boat_orig_name_type_description_2
    boat_orig_name_first_2
    boat_orig_name_middle_2
    boat_orig_name_last_2
    boat_orig_address_1_2
    boat_orig_address_2_2
    boat_orig_fips_2
    boat_orig_province_2
    boat_orig_country_2
    boat_dob_2
    boat_orig_ssn_2
    boat_orig_fein_2
    boat_gender_2
    boat_phone_1_2
    boat_phone_2_2
    boat_title_2
    boat_fname_2
    boat_mname_2
    boat_lname_2
    boat_name_suffix_2
    boat_company_name_2
    boat_prim_range_2
    boat_predir_2
    boat_prim_name_2
    boat_suffix_2
    boat_postdir_2
    boat_unit_desig_2
    boat_sec_range_2
    boat_p_city_name_2
    boat_v_city_name_2
    boat_st_2
    boat_zip5_2
    boat_zip4_2
    boat_county_2
    boat_lien_name_1
    boat_lien_address_1_1
    boat_lien_address_2_1
    boat_lien_city_1
    boat_lien_state_1
    boat_lien_zip_1
    boat_lien_date_1
    boat_lien_indicator_1
    boat_lien_name_2
    boat_lien_address_1_2
    boat_lien_address_2_2
    boat_lien_city_2
    boat_lien_state_2
    boat_lien_zip_2
    boat_lien_date_2
    boat_lien_indicator_2
  }
}
MotorVehicleRecords {
  MotorVehicleRecord {
    mvr_vendor_first_reported_date
    mvr_vendor_date
    mvr_vin
    mvr_model_year
    mvr_make_desc
    mvr_vehicle_type_desc
    mvr_series_desc
    mvr_model_desc
    mvr_body_style_desc
    mvr_major_color_desc
    mvr_minor_color_desc
    mvr_BASE_PRICE
    mvr_Safety_type
    mvr_AIRBAGS
    mvr_TOD_flag
    mvr_Min_Door_count
    mvr_AIRBAG_DRIVER
    mvr_AIRBAG_FRONT_DRIVER_SIDE
    mvr_AIRBAG_FRONT_HEAD_CURTAIN
    mvr_AIRBAG_FRONT_PASS
    mvr_AIRBAG_FRONT_PASS_SIDE
    mvr_documenttypecode
    mvr_orig_net_weight
    mvr_vina_vp_air_conditioning_desc
    mvr_vina_vp_power_steering_desc
    mvr_vina_vp_power_brakes_desc
    mvr_vina_vp_power_windows_desc
    mvr_vina_vp_tilt_wheel_desc
    mvr_vina_vp_roof_desc
    mvr_vina_vp_optional_roof1_desc
    mvr_vina_vp_optional_roof2_desc
    mvr_vina_vp_radio_desc
    mvr_vina_vp_optional_radio1_desc
    mvr_vina_vp_optional_radio2_desc
    mvr_vina_vp_transmission_desc
    mvr_vina_vp_optional_transmission1_desc
    mvr_vina_vp_optional_transmission2_desc
    mvr_vina_vp_anti_lock_brakes_desc
    mvr_vina_vp_front_wheel_drive_desc
    mvr_vina_vp_four_wheel_drive_desc
    mvr_vina_vp_security_system_desc
    mvr_vina_vp_daytime_running_lights_desc
    mvr_vina_number_of_cylinders
    mvr_vina_engine_size
    mvr_fuel_type_name
    mvr_reg_true_license_plate
    mvr_reg_license_plate
    mvr_reg_license_plate_type_code
    mvr_reg_license_plate_type_desc
    mvr_reg_license_state
    mvr_reg_previous_license_plate
    mvr_reg_previous_license_state
    mvr_reg_first_date
    mvr_reg_earliest_effective_date
    mvr_reg_latest_effective_date
    mvr_reg_latest_expiration_date
    mvr_reg_decal_number
    mvr_ttl_number
    mvr_ttl_earliest_issue_date
    mvr_ttl_latest_issue_date
    mvr_ttl_previous_issue_date
    mvr_ttl_status_code
    mvr_ttl_status_desc
    mvr_ttl_odometer_mileage
    mvr_own_1_title
    mvr_own_1_fname
    mvr_own_1_mname
    mvr_own_1_lname
    mvr_own_1_name_suffix
    mvr_own_1_orig_name
    mvr_own_1_orig_sex
    mvr_own_1_did
    mvr_own_1_driver_license_number
    mvr_own_1_dob
    mvr_own_1_ssn
    mvr_own_1_company_name
    mvr_own_1_bdid
    mvr_own_1_fein
    mvr_own_1_addr1
    mvr_own_1_addr2
    mvr_own_1_v_city_name
    mvr_own_1_city
    mvr_own_1_state
    mvr_own_1_zip
    mvr_own_1_county
    mvr_own_1_src_first_date
    mvr_own_1_src_last_date
    mvr_own_1_ultid
    mvr_own_1_orgid
    mvr_own_1_seleid
    mvr_own_1_proxid
    mvr_own_1_powid
    mvr_own_1_empid
    mvr_own_1_dotid
    mvr_reg_1_title
    mvr_reg_1_fname
    mvr_reg_1_mname
    mvr_reg_1_lname
    mvr_reg_1_name_suffix
    mvr_reg_1_orig_name
    mvr_reg_1_orig_sex
    mvr_reg_1_did
    mvr_reg_1_driver_license_number
    mvr_reg_1_dob
    mvr_reg_1_ssn
    mvr_reg_1_company_name
    mvr_reg_1_bdid
    mvr_reg_1_fein
    mvr_reg_1_addr1
    mvr_reg_1_addr2
    mvr_reg_1_v_city_name
    mvr_reg_1_city
    mvr_reg_1_state
    mvr_reg_1_zip
    mvr_reg_1_county
    mvr_reg_1_ultid
    mvr_reg_1_orgid
    mvr_reg_1_seleid
    mvr_reg_1_proxid
    mvr_reg_1_powid
    mvr_reg_1_empid
    mvr_reg_1_dotid
    mvr_lh_1_title
    mvr_lh_1_fname
    mvr_lh_1_mname
    mvr_lh_1_lname
    mvr_lh_1_name_suffix
    mvr_lh_1_lien_date
    mvr_lh_1_orig_name
    mvr_lh_1_orig_sex
    mvr_lh_1_did
    mvr_lh_1_driver_license_number
    mvr_lh_1_dob
    mvr_lh_1_ssn
    mvr_lh_1_company_name
    mvr_lh_1_bdid
    mvr_lh_1_fein
    mvr_lh_1_addr1
    mvr_lh_1_addr2
    mvr_lh_1_v_city_name
    mvr_lh_1_city
    mvr_lh_1_state
    mvr_lh_1_zip
    mvr_lh_1_county
    mvr_lh_1_ultid
    mvr_lh_1_orgid
    mvr_lh_1_seleid
    mvr_lh_1_proxid
    mvr_lh_1_powid
    mvr_lh_1_empid
    mvr_lh_1_dotid
    mvr_le_1_title
    mvr_le_1_fname
    mvr_le_1_mname
    mvr_le_1_lname
    mvr_le_1_name_suffix
    mvr_le_1_orig_name
    mvr_le_1_orig_sex
    mvr_le_1_did
    mvr_le_1_driver_license_number
    mvr_le_1_dob
    mvr_le_1_ssn
    mvr_le_1_company_name
    mvr_le_1_bdid
    mvr_le_1_fein
    mvr_le_1_addr1
    mvr_le_1_addr2
    mvr_le_1_v_city_name
    mvr_le_1_city
    mvr_le_1_state
    mvr_le_1_zip
    mvr_le_1_county
    mvr_le_1_ultid
    mvr_le_1_orgid
    mvr_le_1_seleid
    mvr_le_1_proxid
    mvr_le_1_powid
    mvr_le_1_empid
    mvr_le_1_dotid
    mvr_lo_1_title
    mvr_lo_1_fname
    mvr_lo_1_mname
    mvr_lo_1_lname
    mvr_lo_1_name_suffix
    mvr_lo_1_orig_name
    mvr_lo_1_orig_sex
    mvr_lo_1_did
    mvr_lo_1_driver_license_number
    mvr_lo_1_dob
    mvr_lo_1_ssn
    mvr_lo_1_company_name
    mvr_lo_1_bdid
    mvr_lo_1_fein
    mvr_lo_1_addr1
    mvr_lo_1_addr2
    mvr_lo_1_v_city_name
    mvr_lo_1_city
    mvr_lo_1_state
    mvr_lo_1_zip
    mvr_lo_1_county
    mvr_lo_1_ultid
    mvr_lo_1_orgid
    mvr_lo_1_seleid
    mvr_lo_1_proxid
    mvr_lo_1_powid
    mvr_lo_1_empid
    mvr_lo_1_dotid
    mvr_own_2_title
    mvr_own_2_fname
    mvr_own_2_mname
    mvr_own_2_lname
    mvr_own_2_name_suffix
    mvr_own_2_orig_name
    mvr_own_2_orig_sex
    mvr_own_2_did
    mvr_own_2_driver_license_number
    mvr_own_2_dob
    mvr_own_2_ssn
    mvr_own_2_company_name
    mvr_own_2_bdid
    mvr_own_2_fein
    mvr_own_2_addr1
    mvr_own_2_addr2
    mvr_own_2_v_city_name
    mvr_own_2_city
    mvr_own_2_state
    mvr_own_2_zip
    mvr_own_2_county
    mvr_own_2_src_first_date
    mvr_own_2_src_last_date
    mvr_own_2_ultid
    mvr_own_2_orgid
    mvr_own_2_seleid
    mvr_own_2_proxid
    mvr_own_2_powid
    mvr_own_2_empid
    mvr_own_2_dotid
    mvr_reg_2_title
    mvr_reg_2_fname
    mvr_reg_2_mname
    mvr_reg_2_lname
    mvr_reg_2_name_suffix
    mvr_reg_2_orig_name
    mvr_reg_2_orig_sex
    mvr_reg_2_did
    mvr_reg_2_driver_license_number
    mvr_reg_2_dob
    mvr_reg_2_ssn
    mvr_reg_2_company_name
    mvr_reg_2_bdid
    mvr_reg_2_fein
    mvr_reg_2_addr1
    mvr_reg_2_addr2
    mvr_reg_2_v_city_name
    mvr_reg_2_city
    mvr_reg_2_state
    mvr_reg_2_zip
    mvr_reg_2_county
    mvr_reg_2_ultid
    mvr_reg_2_orgid
    mvr_reg_2_seleid
    mvr_reg_2_proxid
    mvr_reg_2_powid
    mvr_reg_2_empid
    mvr_reg_2_dotid
    mvr_lh_2_title
    mvr_lh_2_fname
    mvr_lh_2_mname
    mvr_lh_2_lname
    mvr_lh_2_name_suffix
    mvr_lh_2_lien_date
    mvr_lh_2_orig_name
    mvr_lh_2_orig_sex
    mvr_lh_2_did
    mvr_lh_2_driver_license_number
    mvr_lh_2_dob
    mvr_lh_2_ssn
    mvr_lh_2_company_name
    mvr_lh_2_bdid
    mvr_lh_2_fein
    mvr_lh_2_addr1
    mvr_lh_2_addr2
    mvr_lh_2_v_city_name
    mvr_lh_2_city
    mvr_lh_2_state
    mvr_lh_2_zip
    mvr_lh_2_county
    mvr_lh_2_ultid
    mvr_lh_2_orgid
    mvr_lh_2_seleid
    mvr_lh_2_proxid
    mvr_lh_2_powid
    mvr_lh_2_empid
    mvr_lh_2_dotid
    mvr_le_2_title
    mvr_le_2_fname
    mvr_le_2_mname
    mvr_le_2_lname
    mvr_le_2_name_suffix
    mvr_le_2_orig_name
    mvr_le_2_orig_sex
    mvr_le_2_did
    mvr_le_2_driver_license_number
    mvr_le_2_dob
    mvr_le_2_ssn
    mvr_le_2_company_name
    mvr_le_2_bdid
    mvr_le_2_fein
    mvr_le_2_addr1
    mvr_le_2_addr2
    mvr_le_2_v_city_name
    mvr_le_2_city
    mvr_le_2_state
    mvr_le_2_zip
    mvr_le_2_county
    mvr_le_2_ultid
    mvr_le_2_orgid
    mvr_le_2_seleid
    mvr_le_2_proxid
    mvr_le_2_powid
    mvr_le_2_empid
    mvr_le_2_dotid
    mvr_lo_2_title
    mvr_lo_2_fname
    mvr_lo_2_mname
    mvr_lo_2_lname
    mvr_lo_2_name_suffix
    mvr_lo_2_orig_name
    mvr_lo_2_orig_sex
    mvr_lo_2_did
    mvr_lo_2_driver_license_number
    mvr_lo_2_dob
    mvr_lo_2_ssn
    mvr_lo_2_company_name
    mvr_lo_2_bdid
    mvr_lo_2_fein
    mvr_lo_2_addr1
    mvr_lo_2_addr2
    mvr_lo_2_v_city_name
    mvr_lo_2_city
    mvr_lo_2_state
    mvr_lo_2_zip
    mvr_lo_2_county
    mvr_lo_2_ultid
    mvr_lo_2_orgid
    mvr_lo_2_seleid
    mvr_lo_2_proxid
    mvr_lo_2_powid
    mvr_lo_2_empid
    mvr_lo_2_dotid
    mvr_own_3_title
    mvr_own_3_fname
    mvr_own_3_mname
    mvr_own_3_lname
    mvr_own_3_name_suffix
    mvr_own_3_orig_name
    mvr_own_3_orig_sex
    mvr_own_3_did
    mvr_own_3_driver_license_number
    mvr_own_3_dob
    mvr_own_3_ssn
    mvr_own_3_company_name
    mvr_own_3_bdid
    mvr_own_3_fein
    mvr_own_3_addr1
    mvr_own_3_addr2
    mvr_own_3_v_city_name
    mvr_own_3_city
    mvr_own_3_state
    mvr_own_3_zip
    mvr_own_3_county
    mvr_own_3_src_first_date
    mvr_own_3_src_last_date
    mvr_own_3_ultid
    mvr_own_3_orgid
    mvr_own_3_seleid
    mvr_own_3_proxid
    mvr_own_3_powid
    mvr_own_3_empid
    mvr_own_3_dotid
    mvr_reg_3_title
    mvr_reg_3_fname
    mvr_reg_3_mname
    mvr_reg_3_lname
    mvr_reg_3_name_suffix
    mvr_reg_3_orig_name
    mvr_reg_3_orig_sex
    mvr_reg_3_did
    mvr_reg_3_driver_license_number
    mvr_reg_3_dob
    mvr_reg_3_ssn
    mvr_reg_3_company_name
    mvr_reg_3_bdid
    mvr_reg_3_fein
    mvr_reg_3_addr1
    mvr_reg_3_addr2
    mvr_reg_3_v_city_name
    mvr_reg_3_city
    mvr_reg_3_state
    mvr_reg_3_zip
    mvr_reg_3_county
    mvr_reg_3_ultid
    mvr_reg_3_orgid
    mvr_reg_3_seleid
    mvr_reg_3_proxid
    mvr_reg_3_powid
    mvr_reg_3_empid
    mvr_reg_3_dotid
    mvr_lh_3_title
    mvr_lh_3_fname
    mvr_lh_3_mname
    mvr_lh_3_lname
    mvr_lh_3_name_suffix
    mvr_lh_3_lien_date
    mvr_lh_3_orig_name
    mvr_lh_3_orig_sex
    mvr_lh_3_did
    mvr_lh_3_driver_license_number
    mvr_lh_3_dob
    mvr_lh_3_ssn
    mvr_lh_3_company_name
    mvr_lh_3_bdid
    mvr_lh_3_fein
    mvr_lh_3_addr1
    mvr_lh_3_addr2
    mvr_lh_3_v_city_name
    mvr_lh_3_city
    mvr_lh_3_state
    mvr_lh_3_zip
    mvr_lh_3_county
    mvr_lh_3_ultid
    mvr_lh_3_orgid
    mvr_lh_3_seleid
    mvr_lh_3_proxid
    mvr_lh_3_powid
    mvr_lh_3_empid
    mvr_lh_3_dotid
    mvr_le_3_title
    mvr_le_3_fname
    mvr_le_3_mname
    mvr_le_3_lname
    mvr_le_3_name_suffix
    mvr_le_3_orig_name
    mvr_le_3_orig_sex
    mvr_le_3_did
    mvr_le_3_driver_license_number
    mvr_le_3_dob
    mvr_le_3_ssn
    mvr_le_3_company_name
    mvr_le_3_bdid
    mvr_le_3_fein
    mvr_le_3_addr1
    mvr_le_3_addr2
    mvr_le_3_v_city_name
    mvr_le_3_city
    mvr_le_3_state
    mvr_le_3_zip
    mvr_le_3_county
    mvr_le_3_ultid
    mvr_le_3_orgid
    mvr_le_3_seleid
    mvr_le_3_proxid
    mvr_le_3_powid
    mvr_le_3_empid
    mvr_le_3_dotid
    mvr_lo_3_title
    mvr_lo_3_fname
    mvr_lo_3_mname
    mvr_lo_3_lname
    mvr_lo_3_name_suffix
    mvr_lo_3_orig_name
    mvr_lo_3_orig_sex
    mvr_lo_3_did
    mvr_lo_3_driver_license_number
    mvr_lo_3_dob
    mvr_lo_3_ssn
    mvr_lo_3_company_name
    mvr_lo_3_bdid
    mvr_lo_3_fein
    mvr_lo_3_addr1
    mvr_lo_3_addr2
    mvr_lo_3_v_city_name
    mvr_lo_3_city
    mvr_lo_3_state
    mvr_lo_3_zip
    mvr_lo_3_county
    mvr_lo_3_ultid
    mvr_lo_3_orgid
    mvr_lo_3_seleid
    mvr_lo_3_proxid
    mvr_lo_3_powid
    mvr_lo_3_empid
    mvr_lo_3_dotid
  }
}
AircraftRecords {
  AircraftRecord {
    air_fract_owner
    air_type_registrant
    air_name
    air_street
    air_street2
    air_city
    air_state
    air_zip_code
    air_region
    air_county_name
    air_country
    air_title
    air_fname
    air_mname
    air_lname
    air_name_suffix
    air_compname
    air_current_flag_1
    air_n_number_1
    air_serial_number_1
    air_mfr_mdl_code_1
    air_year_mfr_1
    air_last_action_date_1
    air_cert_issue_date_1
    air_certification_1
    air_mode_s_code_1
    air_aircraft_mfr_model_code_1
    air_aircraft_mfr_name_1
    air_ac_model_name_1
    air_number_of_engines_1
    air_number_of_seats_1
    air_aircraft_weight_1
    air_aircraft_cruising_speed_1
    air_engine_type_mapped_1
    air_aircraft_type_mapped_1
    air_category_mapped_1
    air_amateur_certification_mapped_1
    air_engine_mfr_model_code_1
    air_engine_mfr_name_1
    air_eng_model_name_1
    air_engine_hp_or_thrust_1
    air_fuel_consumed_1
    air_current_flag_2
    air_n_number_2
    air_serial_number_2
    air_mfr_mdl_code_2
    air_year_mfr_2
    air_last_action_date_2
    air_cert_issue_date_2
    air_certification_2
    air_mode_s_code_2
    air_aircraft_mfr_model_code_2
    air_aircraft_mfr_name_2
    air_ac_model_name_2
    air_number_of_engines_2
    air_number_of_seats_2
    air_aircraft_weight_2
    air_aircraft_cruising_speed_2
    air_engine_type_mapped_2
    air_aircraft_type_mapped_2
    air_category_mapped_2
    air_amateur_certification_mapped_2
    air_engine_mfr_model_code_2
    air_engine_mfr_name_2
    air_eng_model_name_2
    air_engine_hp_or_thrust_2
    air_fuel_consumed_2
    air_current_flag_3
    air_n_number_3
    air_serial_number_3
    air_mfr_mdl_code_3
    air_year_mfr_3
    air_last_action_date_3
    air_cert_issue_date_3
    air_certification_3
    air_mode_s_code_3
    air_aircraft_mfr_model_code_3
    air_aircraft_mfr_name_3
    air_ac_model_name_3
    air_number_of_engines_3
    air_number_of_seats_3
    air_aircraft_weight_3
    air_aircraft_cruising_speed_3
    air_engine_type_mapped_3
    air_aircraft_type_mapped_3
    air_category_mapped_3
    air_amateur_certification_mapped_3
    air_engine_mfr_model_code_3
    air_engine_mfr_name_3
    air_eng_model_name_3
    air_engine_hp_or_thrust_3
    air_fuel_consumed_3
    air_current_flag_4
    air_n_number_4
    air_serial_number_4
    air_mfr_mdl_code_4
    air_year_mfr_4
    air_last_action_date_4
    air_cert_issue_date_4
    air_certification_4
    air_mode_s_code_4
    air_aircraft_mfr_model_code_4
    air_aircraft_mfr_name_4
    air_ac_model_name_4
    air_number_of_engines_4
    air_number_of_seats_4
    air_aircraft_weight_4
    air_aircraft_cruising_speed_4
    air_engine_type_mapped_4
    air_aircraft_type_mapped_4
    air_category_mapped_4
    air_amateur_certification_mapped_4
    air_engine_mfr_model_code_4
    air_engine_mfr_name_4
    air_eng_model_name_4
    air_engine_hp_or_thrust_4
    air_fuel_consumed_4
    air_current_flag_5
    air_n_number_5
    air_serial_number_5
    air_mfr_mdl_code_5
    air_year_mfr_5
    air_last_action_date_5
    air_cert_issue_date_5
    air_certification_5
    air_mode_s_code_5
    air_aircraft_mfr_model_code_5
    air_aircraft_mfr_name_5
    air_ac_model_name_5
    air_number_of_engines_5
    air_number_of_seats_5
    air_aircraft_weight_5
    air_aircraft_cruising_speed_5
    air_engine_type_mapped_5
    air_aircraft_type_mapped_5
    air_category_mapped_5
    air_amateur_certification_mapped_5
    air_engine_mfr_model_code_5
    air_engine_mfr_name_5
    air_eng_model_name_5
    air_engine_hp_or_thrust_5
    air_fuel_consumed_5
  }
}
AssociateRecords {
  AssociateRecord {
    asso_title_1
    asso_first_name_1
    asso_middle_name_1
    asso_last_name_1
    asso_name_suffix_1
    asso_address_1
    asso_city_1
    asso_state_1
    asso_zipcode_1
    asso_phone_1
    asso_ssn_1
    asso_dob_1
    asso_dod_1
    asso_relationship_1
    asso_relationship_type_1
    asso_relationship_confidence_1
    asso_title_2
    asso_first_name_2
    asso_middle_name_2
    asso_last_name_2
    asso_name_suffix_2
    asso_address_2
    asso_city_2
    asso_state_2
    asso_zipcode_2
    asso_phone_2
    asso_ssn_2
    asso_dob_2
    asso_dod_2
    asso_relationship_2
    asso_relationship_type_2
    asso_relationship_confidence_2
    asso_title_3
    asso_first_name_3
    asso_middle_name_3
    asso_last_name_3
    asso_name_suffix_3
    asso_address_3
    asso_city_3
    asso_state_3
    asso_zipcode_3
    asso_phone_3
    asso_ssn_3
    asso_dob_3
    asso_dod_3
    asso_relationship_3
    asso_relationship_type_3
    asso_relationship_confidence_3
    asso_title_4
    asso_first_name_4
    asso_middle_name_4
    asso_last_name_4
    asso_name_suffix_4
    asso_address_4
    asso_city_4
    asso_state_4
    asso_zipcode_4
    asso_phone_4
    asso_ssn_4
    asso_dob_4
    asso_dod_4
    asso_relationship_4
    asso_relationship_type_4
    asso_relationship_confidence_4
    asso_title_5
    asso_first_name_5
    asso_middle_name_5
    asso_last_name_5
    asso_name_suffix_5
    asso_address_5
    asso_city_5
    asso_state_5
    asso_zipcode_5
    asso_phone_5
    asso_ssn_5
    asso_dob_5
    asso_dod_5
    asso_relationship_5
    asso_relationship_type_5
    asso_relationship_confidence_5
    asso_title_6
    asso_first_name_6
    asso_middle_name_6
    asso_last_name_6
    asso_name_suffix_6
    asso_address_6
    asso_city_6
    asso_state_6
    asso_zipcode_6
    asso_phone_6
    asso_ssn_6
    asso_dob_6
    asso_dod_6
    asso_relationship_6
    asso_relationship_type_6
    asso_relationship_confidence_6
    asso_title_7
    asso_first_name_7
    asso_middle_name_7
    asso_last_name_7
    asso_name_suffix_7
    asso_address_7
    asso_city_7
    asso_state_7
    asso_zipcode_7
    asso_phone_7
    asso_ssn_7
    asso_dob_7
    asso_dod_7
    asso_relationship_7
    asso_relationship_type_7
    asso_relationship_confidence_7
    asso_title_8
    asso_first_name_8
    asso_middle_name_8
    asso_last_name_8
    asso_name_suffix_8
    asso_address_8
    asso_city_8
    asso_state_8
    asso_zipcode_8
    asso_phone_8
    asso_ssn_8
    asso_dob_8
    asso_dod_8
    asso_relationship_8
    asso_relationship_type_8
    asso_relationship_confidence_8
    asso_title_9
    asso_first_name_9
    asso_middle_name_9
    asso_last_name_9
    asso_name_suffix_9
    asso_address_9
    asso_city_9
    asso_state_9
    asso_zipcode_9
    asso_phone_9
    asso_ssn_9
    asso_dob_9
    asso_dod_9
    asso_relationship_9
    asso_relationship_type_9
    asso_relationship_confidence_9
    asso_title_10
    asso_first_name_10
    asso_middle_name_10
    asso_last_name_10
    asso_name_suffix_10
    asso_address_10
    asso_city_10
    asso_state_10
    asso_zipcode_10
    asso_phone_10
    asso_ssn_10
    asso_dob_10
    asso_dod_10
    asso_relationship_10
    asso_relationship_type_10
    asso_relationship_confidence_10
    }
}
NeighborRecords {
  NeighborRecord {
    nbr_title_1
    nbr_first_name_1
    nbr_middle_name_1
    nbr_last_name_1
    nbr_name_suffix_1
    nbr_address_1
    nbr_city_1
    nbr_state_1
    nbr_zipcode_1
    nbr_phone_1
    nbr_title_2
    nbr_first_name_2
    nbr_middle_name_2
    nbr_last_name_2
    nbr_name_suffix_2
    nbr_address_2
    nbr_city_2
    nbr_state_2
    nbr_zipcode_2
    nbr_phone_2
    nbr_title_3
    nbr_first_name_3
    nbr_middle_name_3
    nbr_last_name_3
    nbr_name_suffix_3
    nbr_address_3
    nbr_city_3
    nbr_state_3
    nbr_zipcode_3
    nbr_phone_3
    }
}
UtilityRecords {
  UtilityRecord {
    util_type
    util_category
    util_type_desc
    util_connect_date
    util_date_first_seen
    util_record_date
    util_name_first
    util_name_middle
    util_name_last
    util_name_suffix
    util_ssn
    util_dob
    util_drivers_license_state_code
    util_drivers_license
    util_work_phone
    util_phone
    util_addr_dual
    util_addr_type_1
    util_Address1
    util_City1
    util_State1
    util_ZipCode1
    util_county_name_1
    util_addr_type_2
    util_Address2
    util_City2
    util_State2
    util_ZipCode2
    util_county_name_2
    }
}
PilotRecords {
  PilotRecord {
    faa_date_first_seen_1
    faa_date_last_seen_1
    faa_current_flag_1
    faa_letter_code_1
    faa_record_type_1
    faa_pilot_rec_id_1
    faa_region_1
    faa_region_desc_1
    faa_country_1
    faa_med_class_1
    faa_med_class_desc_1
    faa_med_date_1
    faa_med_exp_date_1
    faa_best_ssn_1
    faa_title_1
    faa_fname_1
    faa_mname_1
    faa_lname_1
    faa_name_suffix_1
    faa_Address1
    faa_City1
    faa_State1
    faa_ZipCode1
    faa_county_name_1
    faa_airmen_id_1
    faa_date_first_seen_2
    faa_date_last_seen_2
    faa_current_flag_2
    faa_letter_code_2
    faa_record_type_2
    faa_pilot_rec_id_2
    faa_region_2
    faa_region_desc_2
    faa_country_2
    faa_med_class_2
    faa_med_class_desc_2
    faa_med_date_2
    faa_med_exp_date_2
    faa_best_ssn_2
    faa_title_2
    faa_fname_2
    faa_mname_2
    faa_lname_2
    faa_name_suffix_2
    faa_Address2
    faa_City2
    faa_State2
    faa_ZipCode2
    faa_county_name_2
    faa_airmen_id_2
    faa_date_first_seen_3
    faa_date_last_seen_3
    faa_current_flag_3
    faa_letter_code_3
    faa_record_type_3
    faa_pilot_rec_id_3
    faa_region_3
    faa_region_desc_3
    faa_country_3
    faa_med_class_3
    faa_med_class_desc_3
    faa_med_date_3
    faa_med_exp_date_3
    faa_best_ssn_3
    faa_title_3
    faa_fname_3
    faa_mname_3
    faa_lname_3
    faa_name_suffix_3
    faa_Address3
    faa_City3
    faa_State3
    faa_ZipCode3
    faa_county_name_3
    faa_airmen_id_3
    faa_date_first_seen_4
    faa_date_last_seen_4
    faa_current_flag_4
    faa_letter_code_4
    faa_record_type_4
    faa_pilot_rec_id_4
    faa_region_4
    faa_region_desc_4
    faa_country_4
    faa_med_class_4
    faa_med_class_desc_4
    faa_med_date_4
    faa_med_exp_date_4
    faa_best_ssn_4
    faa_title_4
    faa_fname_4
    faa_mname_4
    faa_lname_4
    faa_name_suffix_4
    faa_Address4
    faa_City4
    faa_State4
    faa_ZipCode4
    faa_county_name_4
    faa_airmen_id_4
    faa_date_first_seen_5
    faa_date_last_seen_5
    faa_current_flag_5
    faa_letter_code_5
    faa_record_type_5
    faa_pilot_rec_id_5
    faa_region_5
    faa_region_desc_5
    faa_country_5
    faa_med_class_5
    faa_med_class_desc_5
    faa_med_date_5
    faa_med_exp_date_5
    faa_best_ssn_5
    faa_title_5
    faa_fname_5
    faa_mname_5
    faa_lname_5
    faa_name_suffix_5
    faa_Address5
    faa_City5
    faa_State5
    faa_ZipCode5
    faa_county_name_5
    faa_airmen_id_5
  }
 }
}
}
`;
